name: Deploy Blog

on:
  push:
    branches:
      - main  # Change to the default branch of your repo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby (for Jekyll)
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'  # Specify the Ruby version

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build the site
      run: |
        bundle exec jekyll build  # For Jekyll
        # hugo  # For Hugo

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site  # For Jekyll
        # publish_dir: ./public  # For Hugo
